export const browserCoreExamples = [
  "avaclaw browser status",
  "avaclaw browser start",
  "avaclaw browser stop",
  "avaclaw browser tabs",
  "avaclaw browser open https://example.com",
  "avaclaw browser focus abcd1234",
  "avaclaw browser close abcd1234",
  "avaclaw browser screenshot",
  "avaclaw browser screenshot --full-page",
  "avaclaw browser screenshot --ref 12",
  "avaclaw browser snapshot",
  "avaclaw browser snapshot --format aria --limit 200",
  "avaclaw browser snapshot --efficient",
  "avaclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "avaclaw browser navigate https://example.com",
  "avaclaw browser resize 1280 720",
  "avaclaw browser click 12 --double",
  'avaclaw browser type 23 "hello" --submit',
  "avaclaw browser press Enter",
  "avaclaw browser hover 44",
  "avaclaw browser drag 10 11",
  "avaclaw browser select 9 OptionA OptionB",
  "avaclaw browser upload /tmp/avaclaw/uploads/file.pdf",
  'avaclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "avaclaw browser dialog --accept",
  'avaclaw browser wait --text "Done"',
  "avaclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "avaclaw browser console --level error",
  "avaclaw browser pdf",
];
